name       : python-netaddr
version    : 0.8.0
release    : 6
source     :
    - https://files.pythonhosted.org/packages/source/n/netaddr/netaddr-0.8.0.tar.gz : d6cc57c7a07b1d9d2e917aa8b36ae8ce61c35ba3fcd1b83ca31c5a0ee2b5a243
homepage   : https://github.com/drkjam/netaddr
license    : BSD-3-Clause
component  : programming.python
summary    : A network address manipulation library for Python
description: |
    A system-independent network address manipulation library for Python.
builddeps  :
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
