name       : python-netaddr
version    : 0.7.19
release    : 2
source     :
    - https://pypi.python.org/packages/0c/13/7cbb180b52201c07c796243eeff4c256b053656da5cfe3916c3f5b57b3a0/netaddr-0.7.19.tar.gz : 38aeec7cdd035081d3a4c306394b19d677623bf76fa0913f6695127c7753aefd
license    : BSD-3-Clause
component  : programming.python
summary    : A network address manipulation library for Python
description: |
    A network address manipulation library for Python
builddeps  :
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
